import type { Contract } from '@/lib/types';

/**
 * Реестр исполненных договоров ООО «ГК «БИОКАТ».
 * Источник — справка о компании, подписанная генеральным директором.
 * Суммы в тысячах рублей, ровно как в справке.
 */
export const contracts: Contract[] = [
  { id: 1, signed: '09.07.2016', finished: '24.04.2017', client: 'ООО «Ленстроймонтаж»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для ВНС и КНС, г. Сочи', amount: 27796.8, status: 'done', services: ['power-supply', 'low-current', 'switchboards'], project: 'sochi-vns' },
  { id: 2, signed: '01.07.2016', finished: '30.04.2017', client: 'ООО «Стройпроект»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для детского сада, г. Пушкино', amount: 7196.7, status: 'done', services: ['power-supply', 'low-current', 'switchboards'], project: 'detsad-pushkino' },
  { id: 3, signed: '15.11.2016', finished: '14.08.2017', client: 'ООО «Гидротехспецмонтаж»', description: 'Изготовление НКУ с шеф-монтажными работами для Саяно-Шушенской ГЭС и Загорской ГАЭС', amount: 11420.6, status: 'done', services: ['switchboards', 'high-voltage'], project: 'sayano-shushenskaya' },
  { id: 4, signed: '10.02.2017', finished: '30.04.2017', client: 'ОАО ОМЗ «Голицинский»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ, п. Большие Вязёмы', amount: 1652.1, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'omz-golitsinsky' },
  { id: 5, signed: '28.03.2017', finished: '07.11.2017', client: 'ООО «Монолит-строй»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для ФГБУ «ВГНКИ», г. Москва', amount: 29155.7, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards', 'automation'], project: 'vgnki' },
  { id: 6, signed: '31.04.2017', finished: '05.12.2017', client: 'ООО «Три восьмёрки»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для гостиницы, г. Москва', amount: 26746.6, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards', 'high-voltage'], project: 'hotel-borodino' },
  { id: 7, signed: '21.02.2018', finished: '12.04.2018', client: 'ООО «Ресурс»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для Рублёвской станции водоподготовки, г. Москва', amount: 50559.4, status: 'done', services: ['power-supply', 'switchboards', 'high-voltage'], project: 'rublevskaya' },
  { id: 8, signed: '25.03.2018', finished: '14.05.2018', client: 'ООО «МЭП»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для ТРЦ «Новомосковский», г. Московский', amount: 5018.0, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'trc-novomoskovsky' },
  { id: 9, signed: '25.03.2018', finished: '14.05.2018', client: 'ООО «МЭП»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для бизнес-парка «Румянцево», г. Москва', amount: 3067.0, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'bp-rumyantsevo' },
  { id: 10, signed: '02.04.2018', finished: '30.11.2018', client: 'ООО «МПХ»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для конноспортивного комплекса «Maxima Park», МО, д. Горки', amount: 13664.0, status: 'done', services: ['power-supply', 'lighting', 'switchboards'], project: 'maxima-park' },
  { id: 11, signed: '31.05.2018', finished: '30.11.2018', client: 'АО «Антарес»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для федерального сотового оператора, г. Москва', amount: 9922.2, status: 'done', services: ['power-supply', 'low-current', 'switchboards'], project: 'antares' },
  { id: 12, signed: '26.11.2018', finished: '09.09.2019', client: 'INDITEX', description: 'Проектные и слаботочные работы, внедрение систем удалённого управления из Испании для розничных магазинов группы на территории России', amount: 68524.8, status: 'done', services: ['low-current', 'automation', 'switchboards'], project: 'inditex' },
  { id: 13, signed: '31.11.2019', finished: '27.09.2020', client: 'ООО «П5Строй»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, г. Москва', amount: 39655.9, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'] },
  { id: 14, signed: '31.05.2019', finished: '30.11.2020', client: 'ООО «Стройкапитал»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, МО, г. Старая Купавна', amount: 79922.2, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards', 'automation'], project: 'kupavino' },
  { id: 15, signed: '11.02.2020', finished: '10.11.2020', client: 'ООО «Стройкапитал»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, МО, г. Ногинск', amount: 7229.5, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'mkd-noginsk' },
  { id: 16, signed: '11.02.2020', finished: '10.11.2020', client: 'ООО «Стройкапитал»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, МО, г. Ногинск', amount: 5399.8, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'mkd-noginsk' },
  { id: 17, signed: '17.04.2021', finished: '10.10.2021', client: 'ООО «Оптимум»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для средней образовательной школы, МО, г. Щёлково', amount: 19399.8, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'fire-safety', 'switchboards'], project: 'school-schelkovo' },
  { id: 18, signed: '11.01.2022', finished: '10.10.2022', client: 'ТСЖ «На Большой Грузинской»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, г. Москва', amount: 24998.45, status: 'done', services: ['fire-safety', 'low-current', 'switchboards'], project: 'bolshaya-gruzinskaya' },
  { id: 19, signed: '12.03.2023', finished: '10.12.2023', client: 'АО «МЭСС»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для Луховицкого авиастроительного завода имени П. А. Воронина, г. Луховицы', amount: 14551.0, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'luhovitsy' },
  { id: 20, signed: '27.05.2024', finished: '21.02.2025', client: 'ООО СЗ «Сьюфорт»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, МО, г. Апрелевка', amount: 39330.5, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'mkd-aprelevka' },
  { id: 21, signed: '31.11.2024', finished: '30.11.2025', client: 'ООО «ГПМ Лобня»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, МО, г. Балашиха', amount: 29756.0, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'mkd-balashikha' },
  { id: 22, signed: '13.01.2025', finished: '30.10.2025', client: 'ООО СЗ «Сьюфорт»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, МО, г. Апрелевка', amount: 38770.8, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'mkd-aprelevka' },
  { id: 23, signed: '21.02.2025', finished: '11.11.2025', client: 'ООО «ГПМ Лобня»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, МО, г. Балашиха', amount: 32855.0, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'mkd-balashikha' },
  { id: 24, signed: '23.02.2025', finished: '30.10.2025', client: 'ООО СЗ «Сьюфорт»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, МО, г. Апрелевка', amount: 37223.0, status: 'done', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'mkd-aprelevka' },
  { id: 25, signed: '21.08.2025', finished: 'В работе', client: 'ООО «ГПМ Лобня»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для многоквартирного жилого дома, МО, г. Балашиха', amount: 33110.0, status: 'active', services: ['power-supply', 'lighting', 'low-current', 'switchboards'], project: 'mkd-balashikha' },
  { id: 26, signed: '20.10.2025', finished: 'В работе', client: 'ООО «Наследие»', description: 'Электромонтажные и слаботочные работы, изготовление НКУ для подстанции 500 кВ «Западная», МО, г. Красногорск', amount: 11213.0, status: 'active', services: ['high-voltage', 'power-supply', 'switchboards'], project: 'ps-zapadnaya' },
];
